"""add_email_verification_tokens

Revision ID: 87ad3dd967b6
Revises: b3e8a12826f6
Create Date: 2026-06-12 16:28:41.624350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ad3dd967b6'
down_revision: Union[str, Sequence[str], None] = 'b3e8a12826f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.Column('backup_location', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_jobs_created_at'), 'backup_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_jobs_id'), 'backup_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_tenant_id'), 'backup_jobs', ['tenant_id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('action_on_expiry', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_tenant_id'), 'data_retention_policies', ['tenant_id'], unique=False)
    op.create_table('third_party_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_test_mode', sa.Boolean(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_integrations_id'), 'third_party_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_third_party_integrations_tenant_id'), 'third_party_integrations', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=500), nullable=True),
    sa.Column('subscribed_events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=500), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('data_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=True),
    sa.Column('legal_hold_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_deletion_requests_id'), 'data_deletion_requests', ['id'], unique=False)
    op.create_index(op.f('ix_data_deletion_requests_tenant_id'), 'data_deletion_requests', ['tenant_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('patient_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('TREATMENT', 'DATA_PROCESSING', 'MARKETING', 'DATA_SHARING', 'RESEARCH', name='consenttype'), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_consents_id'), 'patient_consents', ['id'], unique=False)
    op.create_index(op.f('ix_patient_consents_patient_id'), 'patient_consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_consents_tenant_id'), 'patient_consents', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.add_column('appointments', sa.Column('appointment_number', sa.String(length=50), nullable=False))
    op.alter_column('invoice_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'tax_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_invoice_items_id', table_name='invoice_items')
    op.create_index('ix_invoice_items_invoice', 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_service_id'), 'invoice_items', ['service_id'], unique=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'visit_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_reason',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'balance_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint('invoices_visit_id_key', 'invoices', type_='unique')
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.create_index('ix_invoice_status', 'invoices', ['payment_status'], unique=False)
    op.create_index('ix_invoice_tenant_patient', 'invoices', ['tenant_id', 'patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_created_by'), 'invoices', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoices_visit_id'), 'invoices', ['visit_id'], unique=True)
    op.add_column('patients', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('medical_history', sa.JSON(), nullable=True))
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'),
               type_=sa.String(length=10),
               nullable=True)
    op.alter_column('patients', 'blood_group',
               existing_type=postgresql.ENUM('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', name='bloodgroup'),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('patients', 'registration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('patients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_patients_patient_code', table_name='patients')
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index('ix_payments_id', table_name='payments')
    op.create_index('ix_payment_invoice', 'payments', ['invoice_id'], unique=False)
    op.alter_column('visit_services', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('visit_services', 'visit_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('visit_services', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('visit_services', 'total_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index('ix_visit_services_id', table_name='visit_services')
    op.create_index(op.f('ix_visit_services_service_id'), 'visit_services', ['service_id'], unique=False)
    op.create_index('ix_visit_services_visit', 'visit_services', ['visit_id'], unique=False)
    op.drop_constraint('visit_services_service_id_fkey', 'visit_services', type_='foreignkey')
    op.create_foreign_key(None, 'visit_services', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('visits_appointment_id_key', 'visits', type_='unique')
    op.create_index(op.f('ix_visits_appointment_id'), 'visits', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_appointment_id'), table_name='visits')
    op.create_unique_constraint('visits_appointment_id_key', 'visits', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'visit_services', type_='foreignkey')
    op.create_foreign_key('visit_services_service_id_fkey', 'visit_services', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_visit_services_visit', table_name='visit_services')
    op.drop_index(op.f('ix_visit_services_service_id'), table_name='visit_services')
    op.create_index('ix_visit_services_id', 'visit_services', ['id'], unique=False)
    op.alter_column('visit_services', 'total_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit_services', 'visit_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('ix_payment_invoice', table_name='payments')
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.alter_column('payments', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.create_index('ix_patients_patient_code', 'patients', ['patient_code'], unique=True)
    op.alter_column('patients', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('patients', 'registration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('patients', 'blood_group',
               existing_type=sa.String(length=5),
               type_=postgresql.ENUM('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', name='bloodgroup'),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'),
               nullable=False)
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.drop_column('patients', 'medical_history')
    op.drop_column('patients', 'clinic_id')
    op.drop_index(op.f('ix_invoices_visit_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by'), table_name='invoices')
    op.drop_index('ix_invoice_tenant_patient', table_name='invoices')
    op.drop_index('ix_invoice_status', table_name='invoices')
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_unique_constraint('invoices_visit_id_key', 'invoices', ['visit_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'balance_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'visit_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_invoice_items_service_id'), table_name='invoice_items')
    op.drop_index('ix_invoice_items_invoice', table_name='invoice_items')
    op.create_index('ix_invoice_items_id', 'invoice_items', ['id'], unique=False)
    op.alter_column('invoice_items', 'total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'tax_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('appointments', 'appointment_number')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_patient_consents_tenant_id'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_patient_id'), table_name='patient_consents')
    op.drop_index(op.f('ix_patient_consents_id'), table_name='patient_consents')
    op.drop_table('patient_consents')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_data_deletion_requests_tenant_id'), table_name='data_deletion_requests')
    op.drop_index(op.f('ix_data_deletion_requests_id'), table_name='data_deletion_requests')
    op.drop_table('data_deletion_requests')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_third_party_integrations_tenant_id'), table_name='third_party_integrations')
    op.drop_index(op.f('ix_third_party_integrations_id'), table_name='third_party_integrations')
    op.drop_table('third_party_integrations')
    op.drop_index(op.f('ix_data_retention_policies_tenant_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_backup_jobs_tenant_id'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_id'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_created_at'), table_name='backup_jobs')
    op.drop_table('backup_jobs')
    # ### end Alembic commands ###
