"""remove orphaned clinic_id

Revision ID: 93165481dfd3
Revises: 87ad3dd967b6
Create Date: 2026-06-13 17:00:33.199220

"""
from typing import Sequence, Union
import models
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93165481dfd3'
down_revision: Union[str, Sequence[str], None] = '87ad3dd967b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'clinic_id')
    op.alter_column('third_party_integrations', 'credentials',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=models.integration.EncryptedJSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('third_party_integrations', 'credentials',
               existing_type=models.integration.EncryptedJSON(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('patients', sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
