"""add base_price to services

Revision ID: b3e8a12826f6
Revises: 8b732f780191
Create Date: 2026-02-18 17:32:07.052133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3e8a12826f6'
down_revision: Union[str, Sequence[str], None] = '8b732f780191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_automation_clinic_active'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('idx_lead_clinic_status'), table_name='leads')
    op.drop_index(op.f('idx_lead_follow_up'), table_name='leads')
    op.drop_index(op.f('idx_lead_source_date'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('idx_clinic_active'), table_name='clinics')
    op.drop_index(op.f('idx_clinics_tenant_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_clinic_code'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_email'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_table('clinics')
    op.add_column('ai_interactions', sa.Column('message_content', sa.Text(), nullable=False))
    op.add_column('ai_interactions', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('ai_interactions', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ai_interactions', 'message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('ai_interactions', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_interactions', 'intent_detected',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('idx_interaction_clinic_date'), table_name='ai_interactions')
    op.drop_index(op.f('idx_interaction_lead'), table_name='ai_interactions')
    op.create_index(op.f('ix_ai_interactions_lead_id'), 'ai_interactions', ['lead_id'], unique=False)
    op.drop_constraint(op.f('ai_interactions_clinic_id_fkey'), 'ai_interactions', type_='foreignkey')
    op.drop_constraint(op.f('ai_interactions_lead_id_fkey'), 'ai_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'ai_interactions', 'ai_leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_interactions', 'created_at')
    op.drop_column('ai_interactions', 'response_time_ms')
    op.drop_column('ai_interactions', 'user_message')
    op.drop_column('ai_interactions', 'action_taken')
    op.drop_column('ai_interactions', 'clinic_id')
    op.drop_column('ai_interactions', 'ai_response')
    op.drop_column('ai_interactions', 'confidence_score')
    op.create_foreign_key(None, 'ai_leads', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'api_keys', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('appointments', 'appointment_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('appointments', 'appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NEW_CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'ROUTINE_CHECKUP', name='appointmenttype'),
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='appointmentstatus'),
               existing_nullable=True)
    op.alter_column('appointments', 'reminder_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'checked_in_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_appointment_doctor_date'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_appointment_code'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_constraint(op.f('uq_appointments_appointment_code'), 'appointments', type_='unique')
    op.create_index(op.f('ix_appointments_appointment_code'), 'appointments', ['appointment_code'], unique=True)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('appointments_tenant_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_lead_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'ai_leads', ['ai_lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointments', 'lead_id')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'data_access_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'data_deletion_requests', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'data_deletion_requests', 'users', ['requested_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('doctors_clinic_id_fkey'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('doctors', 'clinic_id')
    op.alter_column('invoice_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'tax_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.create_index('ix_invoice_items_invoice', 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_service_id'), 'invoice_items', ['service_id'], unique=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'visit_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('invoices', 'balance_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('idx_invoice_clinic_date'), table_name='invoices')
    op.drop_index(op.f('idx_invoice_status'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_visit_id'), table_name='invoices', postgresql_where='(visit_id IS NOT NULL)')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.create_index('ix_invoice_status', 'invoices', ['payment_status'], unique=False)
    op.create_index('ix_invoice_tenant_patient', 'invoices', ['tenant_id', 'patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_created_by'), 'invoices', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_payment_status'), 'invoices', ['payment_status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoices_visit_id'), 'invoices', ['visit_id'], unique=True)
    op.drop_constraint(op.f('invoices_appointment_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_clinic_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_tenant_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('invoices', 'line_items')
    op.drop_column('invoices', 'appointment_id')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'clinic_id')
    op.drop_column('invoices', 'paid_date')
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('meta', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'notification_metadata')
    op.create_index(op.f('ix_package_services_package_id'), 'package_services', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_services_service_id'), 'package_services', ['service_id'], unique=False)
    op.drop_constraint(op.f('package_services_service_id_fkey'), 'package_services', type_='foreignkey')
    op.drop_constraint(op.f('package_services_package_id_fkey'), 'package_services', type_='foreignkey')
    op.create_foreign_key(None, 'package_services', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'package_services', 'packages', ['package_id'], ['id'])
    op.drop_column('package_services', 'quantity')
    op.add_column('packages', sa.Column('package_price', sa.Integer(), nullable=False))
    op.alter_column('packages', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_packages_code'), 'packages', ['code'], unique=False)
    op.drop_constraint(op.f('packages_tenant_id_fkey'), 'packages', type_='foreignkey')
    op.create_foreign_key(None, 'packages', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('packages', 'total_price')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('patients', 'allergies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('patients', 'chronic_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('patients', 'medical_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('patients', 'registration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_index(op.f('idx_patient_clinic_email'), table_name='patients')
    op.drop_index(op.f('idx_patient_clinic_phone'), table_name='patients')
    op.drop_index(op.f('idx_patients_tenant_id'), table_name='patients')
    op.drop_constraint(op.f('patients_patient_code_tenant_unique'), 'patients', type_='unique')
    op.drop_constraint(op.f('uq_clinic_patient_code'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('patients_tenant_id_fkey'), 'patients', type_='foreignkey')
    op.drop_constraint(op.f('patients_clinic_id_fkey'), 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'payment_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'INSURANCE', 'WALLET', name='paymentmethod'),
               existing_nullable=False)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('idx_payment_invoice'), table_name='payments')
    op.drop_index(op.f('idx_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index('ix_payment_invoice', 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('payments_tenant_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('services', sa.Column('base_price', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('services', 'tax_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_service_clinic_active'), table_name='services')
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=False)
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('services_clinic_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('services', 'is_package')
    op.drop_column('services', 'clinic_id')
    op.drop_column('services', 'category')
    op.drop_column('services', 'price')
    op.create_foreign_key(None, 'two_factor_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('visit_services', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('visit_services', 'visit_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('visit_services', 'unit_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('visit_services', 'total_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_visit_services_id'), table_name='visit_services')
    op.create_index(op.f('ix_visit_services_service_id'), 'visit_services', ['service_id'], unique=False)
    op.create_index('ix_visit_services_visit', 'visit_services', ['visit_id'], unique=False)
    op.drop_constraint(op.f('visit_services_service_id_fkey'), 'visit_services', type_='foreignkey')
    op.create_foreign_key(None, 'visit_services', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('visits_appointment_id_key'), 'visits', type_='unique')
    op.create_index(op.f('ix_visits_appointment_id'), 'visits', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_appointment_id'), table_name='visits')
    op.create_unique_constraint(op.f('visits_appointment_id_key'), 'visits', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'visit_services', type_='foreignkey')
    op.create_foreign_key(op.f('visit_services_service_id_fkey'), 'visit_services', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_visit_services_visit', table_name='visit_services')
    op.drop_index(op.f('ix_visit_services_service_id'), table_name='visit_services')
    op.create_index(op.f('ix_visit_services_id'), 'visit_services', ['id'], unique=False)
    op.alter_column('visit_services', 'total_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('visit_services', 'visit_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('visit_services', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'two_factor_auth', type_='foreignkey')
    op.add_column('services', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('is_package', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_clinic_id_fkey'), 'services', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.create_index(op.f('idx_service_clinic_active'), 'services', ['clinic_id', 'is_active'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('services', 'tax_percentage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('services', 'estimated_duration_minutes')
    op.drop_column('services', 'base_price')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_tenant_id_fkey'), 'payments', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index('ix_payment_invoice', table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('idx_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_payment_invoice'), 'payments', ['invoice_id', 'payment_date'], unique=False)
    op.alter_column('payments', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'INSURANCE', 'WALLET', name='paymentmethod'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'payment_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'tenant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key(op.f('patients_clinic_id_fkey'), 'patients', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('patients_tenant_id_fkey'), 'patients', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_patients_tenant_id'), table_name='patients')
    op.create_unique_constraint(op.f('uq_clinic_patient_code'), 'patients', ['clinic_id', 'patient_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('patients_patient_code_tenant_unique'), 'patients', ['tenant_id', 'patient_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_patients_tenant_id'), 'patients', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_patient_clinic_phone'), 'patients', ['clinic_id', 'phone'], unique=False)
    op.create_index(op.f('idx_patient_clinic_email'), 'patients', ['clinic_id', 'email'], unique=False)
    op.alter_column('patients', 'registration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('patients', 'medical_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('patients', 'chronic_conditions',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('patients', 'allergies',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.add_column('packages', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.create_foreign_key(op.f('packages_tenant_id_fkey'), 'packages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_packages_code'), table_name='packages')
    op.alter_column('packages', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('packages', 'package_price')
    op.add_column('package_services', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'package_services', type_='foreignkey')
    op.drop_constraint(None, 'package_services', type_='foreignkey')
    op.create_foreign_key(op.f('package_services_package_id_fkey'), 'package_services', 'packages', ['package_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('package_services_service_id_fkey'), 'package_services', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_package_services_service_id'), table_name='package_services')
    op.drop_index(op.f('ix_package_services_package_id'), table_name='package_services')
    op.add_column('notifications', sa.Column('notification_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'meta')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.add_column('invoices', sa.Column('paid_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('line_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_tenant_id_fkey'), 'invoices', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('invoices_clinic_id_fkey'), 'invoices', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('invoices_appointment_id_fkey'), 'invoices', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_invoices_visit_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by'), table_name='invoices')
    op.drop_index('ix_invoice_tenant_patient', table_name='invoices')
    op.drop_index('ix_invoice_status', table_name='invoices')
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('idx_invoices_visit_id'), 'invoices', ['visit_id'], unique=True, postgresql_where='(visit_id IS NOT NULL)')
    op.create_index(op.f('idx_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_invoice_status'), 'invoices', ['payment_status', 'clinic_id'], unique=False)
    op.create_index(op.f('idx_invoice_clinic_date'), 'invoices', ['clinic_id', 'invoice_date'], unique=False)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'balance_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_percentage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('invoices', 'discount_amount',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'visit_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoices', 'patient_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_invoice_items_service_id'), table_name='invoice_items')
    op.drop_index('ix_invoice_items_invoice', table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.alter_column('invoice_items', 'total_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'tax_amount',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'service_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('invoice_items', 'invoice_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('invoice_items', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('doctors', sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_clinic_id_fkey'), 'doctors', 'tenants', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'data_deletion_requests', type_='foreignkey')
    op.drop_constraint(None, 'data_deletion_requests', type_='foreignkey')
    op.drop_constraint(None, 'data_access_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.add_column('appointments', sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_lead_id_fkey'), 'appointments', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('appointments_tenant_id_fkey'), 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_code'), table_name='appointments')
    op.create_unique_constraint(op.f('uq_appointments_appointment_code'), 'appointments', ['appointment_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index(op.f('idx_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_appointments_appointment_code'), 'appointments', ['appointment_code'], unique=False)
    op.create_index(op.f('idx_appointment_doctor_date'), 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.alter_column('appointments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'cancelled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'checked_in_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'reminder_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED', name='appointmentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.Enum('NEW_CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'ROUTINE_CHECKUP', name='appointmenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'ai_leads', type_='foreignkey')
    op.add_column('ai_interactions', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ai_interactions', sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_interactions', sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_interactions', sa.Column('action_taken', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_interactions', sa.Column('user_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ai_interactions', sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_interactions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('ai_interactions_lead_id_fkey'), 'ai_interactions', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ai_interactions_clinic_id_fkey'), 'ai_interactions', 'clinics', ['clinic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_interactions_lead_id'), table_name='ai_interactions')
    op.create_index(op.f('idx_interaction_lead'), 'ai_interactions', ['lead_id'], unique=False)
    op.create_index(op.f('idx_interaction_clinic_date'), 'ai_interactions', ['clinic_id', 'created_at'], unique=False)
    op.alter_column('ai_interactions', 'intent_detected',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ai_interactions', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_interactions', 'message_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ai_interactions', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ai_interactions', 'timestamp')
    op.drop_column('ai_interactions', 'message_content')
    op.create_table('clinics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('secondary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('subscription_tier', postgresql.ENUM('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier'), autoincrement=False, nullable=True),
    sa.Column('subscription_status', postgresql.ENUM('ACTIVE', 'TRIAL', 'SUSPENDED', 'CANCELLED', name='subscriptionstatus'), autoincrement=False, nullable=True),
    sa.Column('subscription_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscription_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('clinics_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('clinics_pkey'))
    )
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_index(op.f('ix_clinics_email'), 'clinics', ['email'], unique=True)
    op.create_index(op.f('ix_clinics_clinic_code'), 'clinics', ['clinic_code'], unique=True)
    op.create_index(op.f('idx_clinics_tenant_id'), 'clinics', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_clinic_active'), 'clinics', ['is_active', 'subscription_status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source', postgresql.ENUM('INSTAGRAM', 'FACEBOOK', 'WHATSAPP', 'WEBSITE', 'REFERRAL', 'WALK_IN', name='leadsource'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST', name='leadstatus'), autoincrement=False, nullable=True),
    sa.Column('initial_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conversation_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_responses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferred_doctor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('preferred_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('service_interest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('converted_to_patient', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('converted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_contacted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_follow', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('follow_up_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('leads_clinic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('leads_patient_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('idx_lead_source_date'), 'leads', ['source', 'created_at'], unique=False)
    op.create_index(op.f('idx_lead_follow_up'), 'leads', ['clinic_id', 'next_follow'], unique=False)
    op.create_index(op.f('idx_lead_clinic_status'), 'leads', ['clinic_id', 'status'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_executed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('automation_rules_clinic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_rules_pkey'))
    )
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('idx_automation_clinic_active'), 'automation_rules', ['clinic_id', 'is_active'], unique=False)
    # ### end Alembic commands ###
