"""describe_your_changes_here

Revision ID: d907586eeb69
Revises: 93165481dfd3
Create Date: 2026-06-13 17:07:10.860979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd907586eeb69'
down_revision: Union[str, Sequence[str], None] = '93165481dfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # 1. Drop existing Foreign Key constraints
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_constraint('invoice_items_service_id_fkey', 'invoice_items', type_='foreignkey')
    
    op.drop_constraint('invoices_tenant_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_patient_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_visit_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    
    op.drop_constraint('payments_tenant_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_invoice_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_created_by_fkey', 'payments', type_='foreignkey')
    
    op.drop_constraint('visit_services_visit_id_fkey', 'visit_services', type_='foreignkey')
    op.drop_constraint('visit_services_service_id_fkey', 'visit_services', type_='foreignkey')


    # 2. Alter column types (Autogenerated)
    op.alter_column('invoice_items', 'id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False, autoincrement=True)
    op.alter_column('invoice_items', 'invoice_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('invoice_items', 'service_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    
    op.alter_column('invoices', 'id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False, autoincrement=True)
    op.alter_column('invoices', 'tenant_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('invoices', 'patient_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('invoices', 'visit_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    op.alter_column('invoices', 'created_by', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    
    op.alter_column('payments', 'id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False, autoincrement=True)
    op.alter_column('payments', 'tenant_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('payments', 'invoice_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('payments', 'created_by', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    
    op.alter_column('visit_services', 'id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False, autoincrement=True)
    op.alter_column('visit_services', 'visit_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=False)
    op.alter_column('visit_services', 'service_id', existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)


    # 3. Recreate Foreign Key constraints
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoice_items_service_id_fkey', 'invoice_items', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    
    op.create_foreign_key('invoices_tenant_id_fkey', 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoices_patient_id_fkey', 'invoices', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoices_visit_id_fkey', 'invoices', 'visits', ['visit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    
    op.create_foreign_key('payments_tenant_id_fkey', 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payments_invoice_id_fkey', 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payments_created_by_fkey', 'payments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    
    op.create_foreign_key('visit_services_visit_id_fkey', 'visit_services', 'visits', ['visit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('visit_services_service_id_fkey', 'visit_services', 'services', ['service_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    
    # 1. Drop constraints for downgrade
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_constraint('invoice_items_service_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_constraint('invoices_tenant_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_patient_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_visit_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('payments_tenant_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_invoice_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_created_by_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('visit_services_visit_id_fkey', 'visit_services', type_='foreignkey')
    op.drop_constraint('visit_services_service_id_fkey', 'visit_services', type_='foreignkey')

    # 2. Revert column types
    op.alter_column('visit_services', 'service_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column('visit_services', 'visit_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('visit_services', 'id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    
    op.alter_column('payments', 'created_by', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column('payments', 'invoice_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('payments', 'tenant_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('payments', 'id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    
    op.alter_column('invoices', 'created_by', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column('invoices', 'visit_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column('invoices', 'patient_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('invoices', 'tenant_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('invoices', 'id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    
    op.alter_column('invoice_items', 'service_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column('invoice_items', 'invoice_id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column('invoice_items', 'id', existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)

    # 3. Recreate original BigInt constraints
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoice_items_service_id_fkey', 'invoice_items', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('invoices_tenant_id_fkey', 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoices_patient_id_fkey', 'invoices', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invoices_visit_id_fkey', 'invoices', 'visits', ['visit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_tenant_id_fkey', 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payments_invoice_id_fkey', 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payments_created_by_fkey', 'payments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('visit_services_visit_id_fkey', 'visit_services', 'visits', ['visit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('visit_services_service_id_fkey', 'visit_services', 'services', ['service_id'], ['id'], ondelete='SET NULL')